name: Deploy to GAE Accurox Dashboard

# Controls when the workflow will run
on:
  push:
    branches: [ master,dev]
  pull_request:
    branches: [ master,dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ secrets.BRANCH}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Creating runtime env_config.js which has config for company
      run: |
        touch ./public/env_config.js
        echo "window.localStorage.setItem('COMPANY_NAME', 'Accurox');" >> ./public/env_config.js
        echo "window.localStorage.setItem('TITLE','Accurox Analytics');" >> ./public/env_config.js
        echo "window.localStorage.setItem('LINK','http://www.accurox.co.uk/');" >> ./public/env_config.js
        echo "window.localStorage.setItem('ICON','https://accurox.co.uk/wp-content/uploads/2022/04/AccuroxLogo.png');" >> ./public/env_config.js
    - name: Setup Node
      uses: actions/setup-node@v2
    - name: Listing
      run: ls
    - name: Building frontend
      run: |
          ls
          npm install --force
          CI= npm run build
    - name: Deploy Development to App Engine
      if: github.ref == 'refs/heads/dev'
      id: deploydev
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: accurox.dev.app.yaml
        version: v1
        project_id: ${{ secrets.GCLOUD_PROJECTID }}
        credentials: ${{ secrets.GCLOUD_APP_DEPLOYER_ACCOUNT }}
    - name: Deploy Production to App Engine
      if: github.ref == 'refs/heads/master'
      id: deployprod
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: accurox.prod.app.yaml
        version: v1
        project_id: ${{ secrets.GCLOUD_PROJECTID }}
        credentials: ${{ secrets.GCLOUD_APP_DEPLOYER_ACCOUNT }}